# Generated by Django 5.1.7 on 2025-04-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventsSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_date",
                    models.DateField(
                        auto_created=True, verbose_name="Дата синхронизации"
                    ),
                ),
                (
                    "created",
                    models.IntegerField(
                        default=0,
                        help_text="Сколько событий было созданно",
                        verbose_name="Созданно",
                    ),
                ),
                (
                    "updated",
                    models.IntegerField(
                        default=0,
                        help_text="Сколько событий было созданно",
                        verbose_name="Обновлено",
                    ),
                ),
                (
                    "changed_at",
                    models.DateField(
                        default=None,
                        help_text="Дата изменения событий",
                        null=True,
                        verbose_name="Дата изменения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Синхронизация Событий",
            },
        ),
    ]
