# Generated by Django 5.1.7 on 2025-04-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventssync",
            name="sync_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время синхронизации"
            ),
        ),
    ]
