# Generated by Django 5.1.7 on 2025-03-29 05:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("73e723f1-07f6-4b04-8db6-512d6b7d41ed"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="places",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("77750828-f295-4cff-89cd-7d4986e336f6"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
