# Generated by Django 5.1.7 on 2025-03-29 08:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_events_id_alter_places_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a3a3f895-fbf1-4cb4-aab2-857c09b4ab33"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="events.places",
            ),
        ),
        migrations.AlterField(
            model_name="places",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("4b5edd29-a6f4-45f8-99bc-2bdcad1e19ad"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
