# Generated by Django 5.1.7 on 2025-03-29 08:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_events_id_alter_events_place_alter_places_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c7aed822-22d6-4809-9edd-e49f1f22c2b3"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.places",
            ),
        ),
        migrations.AlterField(
            model_name="places",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("44d3fe5c-2868-46b1-840e-a181e91e82a9"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
