# Generated by Django 5.1.7 on 2025-04-02 03:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_alter_events_id_alter_events_place_alter_places_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d00341d2-0860-458f-957a-0dc56bc5f01f"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.places",
                verbose_name="Место проведения",
            ),
        ),
        migrations.AlterField(
            model_name="places",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("022919c1-f3e9-456e-b350-ac8428192db4"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
