# Generated by Django 5.1.7 on 2025-04-02 04:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_alter_events_id_alter_events_place_alter_places_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("67023b63-7726-4693-a120-c19a4f62a741"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="places",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1b884c35-03f5-4237-aa9f-eea7bf13bc26"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
